Array.isArray() before calling .push()
Very rarely and randomly in Asterisk 13 (having a bad time trying to reproduce this), when listing some unknown type of events, not clear what (the stack trace isn't helping), the `events` property is not an Array but is set, so it evaluates to true in the check in the library.
Fixed the check to use `Array.isArray()` which is more appropriate.

```
[3463] Unhandled exception.
TypeError: Cannot read property 'push' of undefined
    at Client.parseEvent (/node_modules/ami-io/lib/index.js:221:35)
    at emitOne (events.js:116:13)
    at Client.emit (events.js:211:7)
    at Client.parseMessage (/node_modules/ami-io/lib/index.js:180:44)
    at emitOne (events.js:116:13)
    at Client.emit (events.js:211:7)
    at Client.<anonymous> (/node_modules/ami-io/lib/index.js:168:18)
    at Client.splitMessages (/node_modules/ami-io/lib/index.js:169:22)
    at Client.<anonymous> (/node_modules/ami-io/lib/index.js:145:18)
    at emitOne (events.js:116:13)
```